font_family JetBrainsMono Nerd Font
font_size 10
confirm_os_window_close 0

shell_integration enabled

include matugen.conf

cursor_shape beam
cursor_blink_interval 0.5

# CTRL+SHIFT+N desactivado: kitty abría una OS window nueva (duplicado con SUPER+T de Hyprland)
map ctrl+shift+n discard_event

# CTRL+SHIFT+W desactivado: kitty cerraba la ventana activa (duplicado con SUPER+Q de Hyprland)
map ctrl+shift+w discard_event
